name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-273.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  super_sliver_list:
    path: ../
  logging: ^1.2.0
  headless_widgets:
    git:
      url: https://github.com/widgetbakery/headless_widgets.git
      ref: 18ad55062559aec485c59a383b81569b54f0da09
  provider: ^6.1.1
  context_watch: ^2.0.0-dev.5
  flutter_lorem: ^2.0.0
  pixel_snap: ^0.1.4
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
