name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-273.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  super_sliver_list:
    path: ../
  logging: ^1.2.0
  headless_widgets:
    git:
      url: https://github.com/widgetbakery/headless_widgets.git
      ref: eac8e9d04aaf493d7dec57bd9b0bb26b88a76b43
  super_sliver_list_example_data:
    path: data
  provider: ^6.1.1
  context_watch: ^2.0.0-dev.5
  flutter_lorem: ^2.0.0
  pixel_snap: ^0.1.5
  url_launcher: ^6.2.4
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  uses-material-design: true
