name: Check and Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225 # v2.12.0
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./example
      - name: Check format
        run: dart format . --output=none --set-exit-if-changed
        working-directory: ./example
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: flutter test
